#!/usr/bin/env bash
#
# Install bash and zsh dotfiles environment on OS X.

if [[ $(uname -s) != 'Darwin' ]]; then
    echo "Error: not on OS X"
    exit 1
elif [[ ! -e ~/dotfiles ]]; then
    echo "Error: ~/dotfiles does not exist"
    exit 1
elif [[ -s ~/dotfiles/bak ]]; then # Don't clobber an old backup
    echo "Error: ~/dotfiles/bak already exists"
    exit 1
fi

[[ -z "$(which brew)" ]] && ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade

# Basic tools
brew install \
    ag bash coreutils ctags fasd git gnuplot graphviz \
    httpie jq mysql postgresql ranger reattach-to-user-namespace \
    redis sqlite tmux tree wget youtube-dl zsh

# Editors
brew install macvim --HEAD
brew install emacs --with-cocoa --devel

# Languages
brew install go leiningen opam python python3 rbenv ruby-build

# OCaml config
opam init
opam switch 4.03.0
eval `opam config env`
opam install merlin ocp-indent tuareg utop

# Python config
sudo pip install --upgrade pip
sudo pip install virtualenvwrapper && mkdir -pv ~/repos/python

# Ruby config
rbenv install 2.3.1
rbenv global 2.3.1

# Prezto
git clone --recursive git@github.com:mjwestcott/prezto.git ~/.zprezto

# Tmux Package Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
sudo ~/.tmux/plugins/tpm/bin/install_plugins

# git-prompt
if [[ ! -e ~/.git-prompt.sh ]]; then
    curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# dotfiles
cd ~/dotfiles && mkdir -pv bak
for path in bash/* zsh/* git/* vim/*rc tmux/tmux.conf ag/agignore; do
    file=$(basename $path)
    [[ -e ~/.$file ]] && mv -v ~/.$file bak/.$file
    ln -sfv ~/dotfiles/$path ~/.$file
done

# vim
cd ~/dotfiles/vim/colors && mkdir -pv ~/.vim/colors
for file in *; do
    [[ ! -e ~/.vim/colors/$file ]] && ln -sfv ~/dotfiles/vim/colors/$file ~/.vim/colors/$file
done
