#!/usr/bin/env bash
#
# Install bash and zsh dotfiles environment on macOS.
#
# Manual steps:
#     $ chsh -s $(which zsh)
#     $ brew services start [...]
#     install vim plugins (including fzf)
#     install tmux plugins (prefix + I)
#     set up GitHub SSH key
#     set up git signing key

if [[ $(uname -s) != 'Darwin' ]]; then
    echo "Error: not on macOS"
    exit 1
elif [[ ! -e ~/dotfiles ]]; then
    echo "Error: ~/dotfiles does not exist"
    exit 1
elif [[ -s ~/dotfiles/backup ]]; then # Don't clobber an old backup
    echo "Error: ~/dotfiles/backup already exists"
    exit 1
fi

# Homebrew
[[ -z "$(command -v brew)" ]] && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew update
brew upgrade
brew install ag
brew install awscli
brew install bash
brew install cloc
brew install cmake
brew install coreutils
brew install ctags
brew install devd
brew install dhall
brew install dhall-json
brew install diff-so-fancy
brew install fasd
brew install git
brew install glances
brew install gnupg
brew install go
brew install graphviz
brew install hexyl
brew install highlight
brew install httpie
brew install hub
brew install jq
brew install macvim --HEAD
brew install modd
brew install node
brew install openssl
brew install pipenv
brew install postgresql
brew install python
brew install pyenv
brew install r
brew install ranger
brew install rbenv
brew install reattach-to-user-namespace
brew install redis
brew install rocksdb
brew install shellcheck
brew install sqlite
brew install terraform
brew install tmux
brew install tree
brew install websocat
brew install wget
brew install yarn
brew install yq
brew install youtube-dl
brew install zsh

brew cask install ngrok
brew cask install alacritty

# Custom taps
brew tap dbcli/tap
brew install litecli
brew install pgcli

# Java
brew cask install homebrew/cask-versions/java8
brew install apache-spark
brew install kafka
brew install kafkacat
brew install scala
brew install elasticsearch

# Kubernetes
brew cask install docker
brew install kind
brew install k3d
brew install kubectl
brew install kubectx

# Python Poetry
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

# Rust config
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh \
    && source "$HOME/.cargo/env"

# Jupyter
mkdir -pv ~/repos/python/notebooks \
    && cp ~/dotfiles/jupyter/Pipfile ~/repos/python/notebooks \
    && cp ~/dotfiles/jupyter/imports.ipynb ~/repos/python/notebooks \
    && CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install 3.8.2 \
    && pushd ~/repos/python/notebooks \
    && pipenv install --python ~/.pyenv/versions/3.8.2/bin/python \
    && popd || exit 1

# Ruby config
rbenv install 2.7.1 && rbenv global 2.7.1

# Prezto
if [[ ! -e ~/.zprezto ]]; then
    git clone --recursive https://github.com/mjwestcott/prezto.git ~/.zprezto
    git clone https://github.com/belak/prezto-contrib ~/.zprezto/contrib \
	&& pushd ~/.zprezto/contrib \
        && git submodule init \
        && git submodule update \
	&& popd || exit 1
fi

# Tmux Package Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Dotfiles
cd ~/dotfiles && mkdir -pv backup
for path in shell/bash/* shell/zsh/* readline/* git/* vim/*rc tmux/tmux.conf ag/agignore; do
    file=$(basename "$path")
    [[ -e "$HOME/.$file" ]] && mv -v "$HOME/.$file" "backup/$file"
    ln -sfv "$HOME/dotfiles/$path" "$HOME/.$file"
done

mkdir -pv ~/.config/pgcli && ln -sfv ~/dotfiles/pgcli/config ~/.config/pgcli/config
mkdir -pv ~/.config/litecli && ln -sfv ~/dotfiles/litecli/config ~/.config/litecli/config
mkdir -pv ~/.config/alacritty && ln -sfv ~/dotfiles/alacritty/alacritty_macos.yml ~/.config/alacritty/alacritty.yml
mkdir -pv /usr/local/share/highlight/themes/ && ln -sfv ~/dotfiles/highlight/mjw.theme /usr/local/share/highlight/themes/mjw.theme
mkdir -pv ~/.config/ranger/colorschemes \
    && ln -sfv ~/dotfiles/ranger/rc.conf ~/.config/ranger/rc.conf \
    && ln -sfv ~/dotfiles/ranger/scope.sh ~/.config/ranger/scope.sh \
    && ln -sfv ~/dotfiles/ranger/rifle.conf ~/.config/ranger/rifle.conf \
    && ln -sfv ~/dotfiles/ranger/mjw.py ~/.config/ranger/colorschemes/mjw.py

cd ~/dotfiles/vim/colors && mkdir -pv ~/.vim/colors
for file in *; do
    [[ ! -e ~/.vim/colors/$file ]] && ln -sfv "$HOME/dotfiles/vim/colors/$file" "$HOME/.vim/colors/$file"
done

cd ~/dotfiles/bin && mkdir -pv ~/bin
for file in *; do
    [[ ! -e ~/bin/$file ]] && ln -sfv "$HOME/dotfiles/bin/$file" "$HOME/bin/$file"
done
