"------------------------------------------------------------------------------
" vimrc intended for Python, Go, C, Clojure, Haskell
" by Matt Westcott (mattwestcott.co.uk)

set nocompatible

"------------------------------------------------------------------------------
" vim-plug

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'eagletmt/ghcmod-vim'
Plug 'edkolev/erlang-motions.vim'
Plug 'fatih/vim-go'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'guns/vim-sexp'
Plug 'hail2u/vim-css3-syntax'
Plug 'hdima/python-syntax'
Plug 'itchyny/vim-haskell-indent'
Plug 'junegunn/gv.vim'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'junegunn/seoul256.vim'
Plug 'majutsushi/tagbar', {'on': 'TagbarToggle'}
Plug 'michaeljsmith/vim-indent-object'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'neovimhaskell/haskell-vim'
Plug 'othree/html5.vim'
Plug 'Raimondi/delimitMate'
Plug 'rust-lang/rust.vim'
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'scrooloose/syntastic'
Plug 'Shougo/vimproc', {'do': 'make'}
Plug 'SirVer/ultisnips'
Plug 'sjl/gundo.vim'
Plug 'sjl/vitality.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fireplace', {'for': 'clojure'}
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'tpope/vim-projectionist', {'for': 'clojure'}
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-salve', {'for': 'clojure'}
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'Valloric/ListToggle'
Plug 'Valloric/python-indent'
Plug 'Valloric/YouCompleteMe', {'do': './install.py --gocode-completer --clang-completer'}
Plug 'Valloric/vim-operator-highlight'
call plug#end()

"------------------------------------------------------------------------------
" General Settings

set background=dark
colorscheme minimal

filetype plugin indent on
syntax on

" Undo
set undofile
set undolevels=1000
set undodir=/tmp
set backupdir=/tmp
set dir=/tmp

" History
set history=1000

" Visual
set ruler
set showmode
set lazyredraw
set cursorline
set scrolloff=3
set laststatus=2
set conceallevel=0
set foldlevelstart=99
set diffopt=vertical,filler

" Search
set incsearch
set ignorecase
set smartcase

" Split
set splitbelow
set splitright

" Indent
set smarttab
set tabstop=8
set expandtab
set autoindent
set copyindent
set shiftround
set shiftwidth=4
set softtabstop=4

" Misc
set hidden
set mouse=a
set gdefault
set visualbell
set nojoinspaces
set noerrorbells
set clipboard=unnamed
set backspace=indent,eol,start

if has("gui_running")
    set transp=2
    set linespace=2
    set guioptions-=T
    set guioptions-=l
    set guioptions-=L
    set guioptions-=r
    set guioptions-=R
    set guioptions-=m
    set guioptions-=M
    set guioptions-=e
    set guicursor=a:blinkon0
    set guifont=Menlo:h12
endif

"------------------------------------------------------------------------------
" FileType-Specific Settings

autocmd FileType c
    \ setlocal shiftwidth=4 |
    \ setlocal expandtab

autocmd FileType cpp
    \ setlocal shiftwidth=2 |

autocmd FileType go
    \ setlocal shiftwidth=8 |
    \ setlocal noexpandtab

autocmd FileType html
    \ setlocal shiftwidth=2

autocmd FileType lisp,clojure,scheme
    \ setlocal shiftwidth=2

autocmd FileType python
    \ setlocal textwidth=79 |
    \ setlocal shiftwidth=4 |
    \ setlocal expandtab

autocmd FileType ocaml
    \ setlocal shiftwidth=2 |
    \ setlocal expandtab

autocmd FileType sh
    \ setlocal textwidth=80

autocmd FileType markdown
    \ syntax match Comment /\%^---\_.\{-}\.\.\.$/ " YAML front-matter

autocmd BufWritePre * :%s/\s\+$//e
autocmd BufNewFile,BufRead *bash* let g:is_bash=1
autocmd FileType gitcommit setlocal spell! spelllang=en_gb
autocmd FileType vim,html let b:delimitMate_matchpairs = "(:),[:],{:}"
autocmd BufNewFile,BufRead \*.{md,mdwn,mkd,mkdn,mark\*} set filetype=markdown
autocmd BufNewFile,BufRead *.erl,*.es,*.hrl,*.yaws,*.xrl setf erlang

"------------------------------------------------------------------------------
" Mappings (see also Plugin section)

let mapleader=" "

" UK keyboards...
inoremap § <ESC>

" Keep search matches in the middle of the window.
nnoremap * *zzzv
nnoremap # #zzzv
nnoremap n nzzzv
nnoremap N Nzzzv

noremap Q gq
nnoremap Q gqap
nnoremap Y y$
nnoremap j gj
nnoremap k gk
vnoremap < <gv
vnoremap > >gv

" The secret sauce.
noremap <C-h> b
noremap <C-l> w
noremap <C-j> 10gj
noremap <C-k> 10gk
noremap <C-n> <C-^>

" Window switching.
nnoremap <tab> <C-w>w
nnoremap <S-tab> <C-w>W
noremap <leader>h <C-w>h
noremap <leader>l <C-w>l
noremap <leader>k <C-w>k
noremap <leader>j <C-w>j

" These create newlines like o and O but stay in normal mode.
nnoremap <silent> zj o<Esc>k
nnoremap <silent> zk O<Esc>j

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :qa<CR>
noremap <leader>cd :cd %:p:h<cr>

" Replace what is under the cursor globally, prompted for each word.
nnoremap <leader>r :%s/\<<C-r><C-w>\>//c<left><left>

" :%s/old/new/c replaces 'old' with 'new' globally, prompted for each word.
nnoremap <leader>R :%s//c<left><left>

" Editing and loading vimrc.
noremap <silent> <leader>v :e $MYVIMRC<CR>
noremap <silent> <leader>.v :so $MYVIMRC<CR>
nnoremap <leader>U :PlugUpdate<CR>

" Toggle functions.
nnoremap <silent> <leader>Z :call ToggleNumber()<CR>
function! ToggleNumber()
    set number!
endfunction

nnoremap <silent> <leader>X :call ToggleSyntax()<CR>
function! ToggleSyntax()
    if exists("g:syntax_on") | syntax off | else | syntax enable | endif
endfunction

nnoremap <silent> <leader>C :call ToggleColorColumn()<CR>
function! g:ToggleColorColumn()
  if &colorcolumn != ''
    setlocal colorcolumn&
  else
    setlocal colorcolumn=+1
  endif
endfunction

"------------------------------------------------------------------------------
" fzf all the things

nnoremap <leader>/ :BLines<CR>
nnoremap <leader>t :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>m :History<CR>
nnoremap <leader>p :GitFiles<CR>

nnoremap ,, :Ag<space><C-R><C-W><CR>
nnoremap ,g :Ag<space>
nnoremap ,v :FZF ~<CR>
nnoremap ,l :Locate<space>
nnoremap ,c :Commits<CR>
nnoremap ,b :BCommits<CR>
nnoremap ,/ :Lines<CR>
nnoremap ,: :Commands<CR>
nnoremap ,w :Windows<CR>
nnoremap ,s :Snippets<CR>
nnoremap ,m :Maps<CR>
nnoremap ,M :Marks<CR>
nnoremap ,H :Helptags<CR>
nnoremap ,C :Colors<CR>
nnoremap ,h: :History:<CR>
nnoremap ,h/ :History/<CR>

"------------------------------------------------------------------------------
" vim-operator-highlight

let g:ophigh_highlight_link_group = "Operator"
let g:ophigh_filetypes_to_ignore = { "haskell": 1,
                                   \ "ocaml": 1,
                                   \ "erlang": 1,
                                   \ "clojure": 1,
                                   \ "lisp": 1,
                                   \ "zsh": 1,
                                   \ "bash": 1,
                                   \ "sh": 1,
                                   \ "text": 1,
                                   \ "gitcommit": 1}

"------------------------------------------------------------------------------
" rainbow-parentheses

nnoremap <leader>P :RainbowParentheses!!<CR>
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
let g:rainbow#blacklist = [203, 253, 231, 224, 121, 159, 72, '#f6f6f6']

"------------------------------------------------------------------------------
" vim-fireplace

autocmd FileType clojure nnoremap <leader><leader> :Eval<CR>

"------------------------------------------------------------------------------
" NERDTree

nnoremap <leader>N :NERDTreeToggle<CR>

"------------------------------------------------------------------------------
" TagBar

nnoremap <leader>T :TagbarToggle<CR>

"------------------------------------------------------------------------------
" NeoVim

let g:python_host_prog = '/usr/local/bin/python'

"------------------------------------------------------------------------------
" python-syntax

let g:python_highlight_builtins = 0

"------------------------------------------------------------------------------
" rust.vim

let g:rustfmt_autosave = 1

"------------------------------------------------------------------------------
" Clang-format

noremap <leader>cf :pyf ~/dotfiles/vim/misc/clang-format.py<CR>

"------------------------------------------------------------------------------
" markdown syntax

let g:markdown_syntax_conceal = 0
let g:markdown_fenced_languages = ['python', 'go', 'c', 'clojure', 'haskell',
                                  \ 'bash=sh', 'zsh', 'html', 'css', 'javascript']

"------------------------------------------------------------------------------
" ListToggle

let g:lt_location_list_toggle_map = '<leader>i'
let g:lt_quickfix_list_toggle_map = '<leader>u'
let g:lt_height = 10

"------------------------------------------------------------------------------
" EasyAlign

vmap <Enter> <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

"------------------------------------------------------------------------------
" vim-fugitive

nmap <leader>s :Gstatus<CR>gg<C-n>
nnoremap <leader>d :Gdiff<CR>

"------------------------------------------------------------------------------
" gv.vim

nmap <leader>G :GV<CR>o
nmap <leader>V :GV!<CR>o

"------------------------------------------------------------------------------
" vim-go

let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 0

" Since 'g' is taken by GoTo commands...
nmap <leader>or <Plug>(go-run)
nmap <leader>ob <Plug>(go-build)
nmap <leader>ot <Plug>(go-test)
nmap <leader>oc <Plug>(go-coverage)
nmap <leader>os <Plug>(go-implements)
nmap <leader>oi <Plug>(go-info)
nmap <leader>oe <Plug>(go-rename)
nmap <leader>ds <Plug>(go-def-split)
nmap <leader>dv <Plug>(go-def-vertical)
nmap <leader>dt <Plug>(go-def-tab)

"------------------------------------------------------------------------------
" TagBar

let g:tagbar_sort = 0
let g:tagbar_singleclick = 1
let g:tagbar_show_visibility = 1
let g:tagbar_iconchars = ['▸', '▾']

"------------------------------------------------------------------------------
" delimitMate

let delimitMate_quotes = ""
let delimitMate_expand_cr = 1

"------------------------------------------------------------------------------
" YouCompleteMe

let g:ycm_complete_in_strings = 1
let g:ycm_complete_in_comments = 1
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_min_num_identifier_candidate_chars = 4
let g:ycm_semantic_triggers = {'haskell' : ['.']}
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_extra_conf_globlist = ['~/repos/*', '!~/*']

nnoremap <leader>g :YcmCompleter GoTo<CR>
nnoremap <leader>yd :YcmCompleter GoToDefinition<CR>
nnoremap <leader>yc :YcmCompleter GoToDeclaration<CR>

"------------------------------------------------------------------------------
" UltiSnips

let g:snips_author = 'Matt Westcott'
let g:UltiSnipsExpandTrigger = "``"
let g:UltiSnipsEditSplit = "vertical"
let g:UltiSnipsListSnippets = "<C-x>"
let g:ultisnips_python_style = "google"
let g:ultisnips_python_quoting_style = "double"
let g:ultisnips_python_triple_quoting_style = "double"
let g:UltiSnipsJumpBackwardTrigger = "<Left>"
let g:UltiSnipsJumpForwardTrigger = "<Right>"
let g:UltiSnipsSnippetsDir = "~/dotfiles/vim/ultisnips"
let g:UltiSnipsSnippetDirectories=[$HOME.'/dotfiles/vim/ultisnips']

"------------------------------------------------------------------------------
" syntastic

let g:syntastic_aggregate_errors = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs = 0
let g:syntastic_check_on_open = 0
let g:syntastic_auto_loc_list = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--select=F,C9 --max-complexity=10'
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { "mode": "active",
                           \ "active_filetypes": [],
                           \ "passive_filetypes": ['html'] }

nnoremap <leader>S :SyntasticReset<CR>

"------------------------------------------------------------------------------
" merlin (assumes an installation via OPAM)

let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"

"------------------------------------------------------------------------------
" ocp-indent (assumes an installation via OPAM)

set rtp^="/Users/mattwestcott/.opam/system/share/ocp-indent/vim"

"------------------------------------------------------------------------------
" fuzzynotes

let g:notes_dir = $NOTESDIR

function! g:Slugify(str)
    return join(split(tolower(a:str), '\W\+'), '-')
endfunction

function! g:NoteTemplate(desc)
    call append(0, "---")
    call append(1, "tags: []")
    call append(2, "description: " . a:desc)
    call append(3, "...")
endfunction

function! g:NoteSink(output)
    if len(a:output) == 2
        let query = a:output[0]
        let key = a:output[1]
        if key == "enter"
            let filename = g:Slugify(query) . ".md"
            exec "edit" join([g:notes_dir, filename], "/")
            call g:NoteTemplate(query)
        endif
    elseif len(a:output) == 3
        let key = a:output[1]
        let data = a:output[2]
        " Data is expected as '{filename}:{description} | {modified} | {tags}'
        let filename = split(data, ":")[0]
        if key == "ctrl-r"
            exec "!rm -i" join([g:notes_dir, filename], "/")
        else
            exec "edit" join([g:notes_dir, filename], "/")
        endif
    endif
endfunction

command! Notes call fzf#run({
  \ 'source':  'fuzzynotes show',
  \ 'sink*':    function('g:NoteSink'),
  \ 'down':    '~40%',
  \ 'options': '--exact --ansi -d ":" --with-nth 2.. --prompt="Notes> " ' .
  \            '--expect=enter,ctrl-r --print-query'
  \})

nnoremap <leader>n :Notes<CR>
