#!/usr/bin/env bash
#
# Assumes dotfiles and modd already exist, ~/bin is on PATH

[[ -n $NOTESDIR ]] || echo 'install fuzzynotes: NOTESDIR not set' && exit 1

git clone https://gitlab.com/mjwestcott/notes.git $NOTESDIR
cd ~/dotfiles/notes && mkdir -p ~/bin
ln -sfv ~/dotfiles/notes/fuzzynotes ~/bin/fuzzynotes

mkdir -p $NOTESDIR/.fuzzynotes && cd $NOTESDIR/.fuzzynotes
touch synclog && touch cache
ln -sfv ~/dotfiles/notes/modd.conf $NOTESDIR/.fuzzynotes/modd.conf
