#!/usr/bin/env bash
#
# Assumes dotfiles already exists and ~/bin is on PATH.
# modd is required for the autosync feature.

[[ -n $NOTESDIR ]] || echo 'install fuzzynotes: NOTESDIR not set' && exit 1

git clone https://gitlab.com/mjwestcott/notes.git $NOTESDIR
cd ~/dotfiles/notes && mkdir -p ~/bin
ln -sfv ~/dotfiles/notes/fuzzynotes ~/bin/fuzzynotes

mkdir -p $NOTESDIR/.fuzzynotes && cd $NOTESDIR/.fuzzynotes
touch synclog
echo "hash: ~\ndata: ~" > cache
ln -sfv ~/dotfiles/notes/modd.conf $NOTESDIR/.fuzzynotes/modd.conf
